### ISSUE TITLE
 Cannot find module 'src/app/secret' or its corresponding type declarations

### ISSUE THREAD

**Issue by rm-rfmukul** [shekhutsav1962001/CanteenManagement#13]
Can't resolve 'src/app/secret' in 'CanteenManagement\frontend\canteen\src\app\user\myorders' 

I am not able t0 find any file or folder in the location. https://github.com/shekhutsav1962001/CanteenManagement/tree/master/frontend/canteen/src/app

Also, as you can see line no. 7 looks incomplete.
```
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';
import { UserService } from 'src/app/services/user.service';
import { WebsocketService } from 'src/app/services/websocket.service';
import { data } from 'src/app/secret'
@Component({
  selector: 'app-myorders',
  templateUrl: './myorders.component.html',
  styleUrls: ['./myorders.component.css']
})
```
Kindly help me resolving this issue.

**Comment by shekhutsav1962001** [comment]
You have to create secret.ts file CanteenManagement\frontend\canteen\src\app in this path content of that file is as follow

```typescript
export const data = {
  MID: "XXXXX", // paytm provide
  WEBSITE: "XXXXX", // paytm provide
  INDUSTRY_TYPE_ID: "XXXXX", // paytm provide
  CHANNEL_ID: "XXXXX", // paytm provide
  CALLBACK_URL: "https://..../callback2", // Call back URL that i want to redirect after payment fail or success
  PAYMENT_URL:"https://..../pay"
};
```


You can go to this website and https://business.paytm.com and grab the above details from there and for the payment URL and callback URL you can go through this repo https://github.com/shekhutsav1962001/PaytmGatewayNode take idea .
