### ISSUE TITLE
A bucket need to use cloud storage 

### ISSUE THREAD

**Issue by Manipraba** [shekhutsav1962001/CanteenManagement#14]
App crashed - waiting for file changes before starting

**Comment by shekhutsav1962001** [comment]
You might need to add a config file inside `/backend/` folder

That will will be something like this 

```
{
  "type": "",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}

```

which can be downloaded from GCP save this file with name `cloudconfig.json` as


Now add this file's name in the `.ENV` file as below 

```
KEYFILE= cloudconfig.json
```

Hopefully, It will resolve this issue. Fell free to open if you still face any issue
